# Features required
include_features:
  - price
  - num_subscribers
  - avg_rating
  - num_lectures
  - content_length_min
  - category
  - subcategory
  - language
  - instructor_name

# Clean up parameters:
# include values more than indicated
clean_up:
  price: 10
  num_subscribers: 0


# Categorical count vizualization
# visualization only includes indicated here
categorical_count_visualization:
  - category

# Numerical versus Categorical EDA visualization
numerical_vs_categorical_eda_visualization:
  num_subscribers: category
  price: category


kmodes:
  cluster: 1
  iteration: 5
  categorical_features:
    - instructor_name
  numerical_features:
    - price
    - num_subscribers
    - avg_rating
    - num_lectures
    - content_length_min
