
default_language_version:
  # default language version for each language used in the repository
  python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer


-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black


-   repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]


-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-typing-imports==1.10.1,
            flake8-bugbear,
            flake8-comprehensions,
            flake8-mutable,
            flake8-simplify,
        ]



-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-dataclasses
        - types-DateTimeRange
        - types-python-dateutil
        - types-pytz
        - types-PyYAML
        - types-requests
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: [
          --install-types,
          --ignore-missing-imports,
          --check-untyped-defs,
          --disallow-untyped-defs,
          --strict-equality,
          --namespace-packages,
          --disallow-subclassing-any,
          --disallow-any-explicit,
          ]
